### ISSUE TITLE
failed to load macro

### ISSUE THREAD

**Issue by dengyunsheng250** [tokio-rs/mini-redis#148]
when open rs file in cmd/* like ping.rs, set.rs get.rs, i got the error message
```
failed to load macro: Failed to get file metadata for ~/mini-redis/target/debug/deps/libtracing_attributes-404da065c25ce003.so: No such file or directory (os error 2)
```

**Comment by Darksonn** [comment]
That sounds like a problem with your local setup. You can try deleting the `~/mini-redis/target` folder or updating your rust-analyzer install.
