### ISSUE TITLE
Apparent memory leak of spawned tasks

### ISSUE THREAD

**Issue by jebrosen** [tokio-rs/mini-redis#38]
I believe there is some form of memory leak, and this was discussed some in the Discord channel `#tokio-users` recently. This graph should illustrate it pretty well:

[![Memory leak graph](https://media.discordapp.net/attachments/500336333500448798/701139689360326656/20200418_113828.png)](https://media.discordapp.net/attachments/500336333500448798/701139689360326656/20200418_113828.png)

The orange 6.2MB are a single allocation by `tracing-subscriber`, the green are `RawTask`s that are allocated via `spawn`, and the blue are something in `broadcast`. The workload is just running `while true; do target/release/cli get k; done` for a while (perhaps after setting a value for `k`, but I believe it doesn't actually matter).

As far as I can tell, the spawned tasks have actually completed. A different implementation (using `watch` instead of `broadcast`) fixes it. Another project using `broadcast` does not have a similar issue. My hunch is that there is some kind of reference cycle, maybe in part because the shutdown coordination is bidirectional, but I have not looked more closely yet.

**Comment by Darksonn** [comment]
If you modify Tokio to print when `Arc<WaitNode>` is created and dropped inside `broadcast`, you will see that it creates one for every connection, but none of them are dropped until the application closes.

**Comment by carllerche** [comment]
Thanks for the report. I will try to look later today. My guess, w/o looking, is that it is a similar problem as the old semaphore had. If that is a case, it will need a similar rework as https://github.com/tokio-rs/tokio/pull/2325

**Comment by hawkw** [comment]
@carllerche do you think `broadcast` can easily be modified to use the semaphore?

**Comment by carllerche** [comment]
Open PR here: https://github.com/tokio-rs/tokio/pull/2509

**Comment by carllerche** [comment]
I have been running the reproduction using the PR linked above and memory is stable for me.

**Comment by carllerche** [comment]
Fixed w/ the `tokio` release.
