### ISSUE TITLE
how to config memory to be used?

### ISSUE THREAD

**Issue by hiqsociety** [tokio-rs/mini-redis#84]
how to config memory to be used?

**Comment by Darksonn** [comment]
What do you mean?

**Comment by hiqsociety** [comment]
set a maxmemory on how much memory to use

**Comment by Darksonn** [comment]
Mini-redis will never remove keys unless instructed to or the key expires, and having the database stored on disk is not supported, so it will use the memory it takes to store the keys it is given.
