### ISSUE TITLE
updates?

### ISSUE THREAD

**Issue by adsick** [tokio-rs/mini-redis#87]
mini-redis is used for learning async programming in Rust, but I feel like it needs to be updated.

**Comment by adsick** [comment]
consider this for example: https://github.com/tokio-rs/mini-redis/blob/tutorial/src/connection.rs#L27-L30

**Comment by adsick** [comment]
also I did not found any CHANGELOG of Tokio, so can't determine if that was fixed.

**Comment by Darksonn** [comment]
The particular thing that the comment is referring to is [tokio#2428][2], which we ended up deciding against. You can find the changelog [here][1].

[1]: https://github.com/tokio-rs/tokio/blob/master/tokio/CHANGELOG.md
[2]: https://github.com/tokio-rs/tokio/issues/2428

**Comment by adsick** [comment]
Thanks

**Comment by adsick** [comment]
Thanks

**Comment by Darksonn** [comment]
Hm, it seems like we have both a tutorial and a master branch, and I don't remember why. This has been fixed on the master branch a while ago. Will investigate...
